name = "tutasnack-backend"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[vars]
USE_NEON_ADAPTER = "true"

[placement]
mode = "smart"

[env.production]
vars = { NODE_ENV = "production" }
